/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;

import dao.Conexao;
import dao.UsuarioDAO;
import model.Usuario;
import model.Projeto;;

public class Contatos extends javax.swing.JFrame {

public static Usuario usuario;
public static Projeto projeto;
    /**
     * Creates new form Contatos
     */
     public Contatos(Usuario usuario, Projeto projeto) {
        this.usuario = usuario; 
        this.projeto = projeto;
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelContatos = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelContatos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelContatos.setText("Contatos");

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        
         UsuarioDAO trazer = new UsuarioDAO(Conexao.conectar());
         
        try {
            ArrayList<Usuario> contatos = trazer.readTodosUsuarios(this.usuario);

            int i = 10;
            for(Usuario p : contatos) { 
        
                JButton btn = new JButton(p.getNomeUsuario());
                btn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
                btn.setBounds(i, 80, 150, 50);
                add(btn);

                btn.addActionListener(new ActionListener() { 
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        CriarNovaConversa pp = new CriarNovaConversa(usuario,p);
                        dispose();
                        pp.iniciar();
                    }
                });
                
                i += 160;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }    
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelContatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 618, Short.MAX_VALUE)
                .addComponent(btnVoltar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addContainerGap(443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>               
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ProjetoPrincipal pp = new ProjetoPrincipal(this.projeto, this.usuario);
        dispose();
        pp.iniciar();
    }

    /**
     * @param args the command line arguments
     */
     
    public void iniciar() {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Contatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Contatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Contatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Contatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       this.setVisible(true);
    }
      
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel labelContatos;
    // End of variables declaration                   
}