package view;

import model.Usuario;

import dao.Conexao;
import dao.MensagemDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Mensagem;
import model.Projeto;
import model.Usuario;
/**
 *
 * @author vitor
 */
public class CriarNovaConversa extends javax.swing.JFrame {
public static Usuario usuario;
public static Usuario destinatario;
Mensagem msg = new Mensagem();

   /**
     * Creates new form CriarNovaConversa
     */
    public CriarNovaConversa(Usuario usuario,Usuario destinatario) {
        this.usuario = usuario;  
        this.destinatario = destinatario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelContatos = new javax.swing.JLabel();
        Email1 = new javax.swing.JTextField();
        btnPassar = new javax.swing.JButton();
        painelChat = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelContatos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelContatos.setText("Mande sua mensagem para " + this.destinatario.getApelido());
        

        Email1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Email1.setMaximumSize(new java.awt.Dimension(1920, 1920));
        Email1.setName(""); // NOI18N
       

        btnPassar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPassar.setText(">");
        btnPassar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelChatLayout = new javax.swing.GroupLayout(painelChat);
        painelChat.setLayout(painelChatLayout);
        painelChatLayout.setHorizontalGroup(
            painelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        painelChatLayout.setVerticalGroup(
            painelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        
         painelChat.setBackground(Color.white); 
         SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy HH:mm:ss ");
         MensagemDAO trazer = new MensagemDAO(Conexao.conectar());
        
        try{
            ArrayList<Mensagem> mensagens = trazer.readMensagemUsuario(this.usuario, this.destinatario);
            
            
            int i = 0;
            for(Mensagem p : mensagens) {
                
                GregorianCalendar data = p.getDataHoraEnvio();
                String dataFormatada = sdf.format(p.getDataHoraEnvio().getTime());
//                JLabel labelData = new JLabel(dataFormatada);     
                JLabel estado = new JLabel(p.getRemetente().getApelido()+  "\n\""+p.getTexto()+"\""+p.getEstado()+" - "+" - "+dataFormatada);
                estado.setBounds(15,-50+i,600,200);
                
                estado.setText("<html>" + p.getRemetente().getApelido()+"<br>"+" - "+p.getTexto()+"-"+"<br>"+p.getEstado()+" - "+dataFormatada+"</html>" );

                     painelChat.add(estado);
                     add(painelChat);
                i+=75;
            }
            
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPassar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelContatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(painelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(painelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPassar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Email1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

                                  

    private void btnPassarActionPerformed(java.awt.event.ActionEvent evt) {
                                            
/////////////////////////////////////                                      
        MensagemDAO trazer = new MensagemDAO(Conexao.conectar());
        
        String msgEnviar = Email1.getText();
        if(msgEnviar.equals("")) {
        	JOptionPane.showMessageDialog(null, "Digite sua mensagem", "", JOptionPane.ERROR_MESSAGE);
        } else{
            msg.setTexto(msgEnviar);
            msg.setDestinatario(destinatario);
            msg.setRemetente(usuario);
            
            trazer.createMensagem(msg);
            dispose();
            CriarNovaConversa cnc = new CriarNovaConversa(this.usuario, this.destinatario );
            cnc.iniciar();
        }
    }
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	ListaProjetos listaProjeto = new ListaProjetos(this.usuario);
        dispose();
        listaProjeto.iniciar();
      
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarNovaConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarNovaConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarNovaConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarNovaConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     this.setVisible(true);   
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Email1;
    private javax.swing.JButton btnPassar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel labelContatos;
    private javax.swing.JPanel painelChat;
    // End of variables declaration                   
}