/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AlocaUsuarioProjetoDAO;
import dao.Conexao;
import model.Usuario;
import model.Projeto;

import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author Fernanda
 */
public class ListaExcluirUsuario extends javax.swing.JFrame {
    public static Usuario usuario;
    public static Projeto projeto;
    
    /**
     * Creates new form ListaExcluirUsuario
     */
    public ListaExcluirUsuario(Usuario u, Projeto p) {
        this.usuario = u;
        this.projeto = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelUsuarios = new javax.swing.JLabel();
        btnAdicionarUsuario = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUsuarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUsuarios.setText("Usuários");

        btnAdicionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdicionarUsuario.setText("Adicionar usuário");
        btnAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUsuarioActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        AlocaUsuarioProjetoDAO aDAO = new AlocaUsuarioProjetoDAO(Conexao.conectar());
        ArrayList<Usuario> usuarioPresente = aDAO.readUsuarioProjeto(this.usuario, this.projeto);

        int i = 80;
        for(Usuario u : usuarioPresente) {

            JLabel nome = new JLabel(u.getNomeUsuario());
            nome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            nome.setBounds(20, i, 150, 50);
            add(nome);

            JButton btn = new JButton("Excluir");
            btn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            btn.setBounds(150, i, 150, 50);
            add(btn);

            btn.addActionListener(new ActionListener() { 
                @Override
                public void actionPerformed(ActionEvent e) {
                    AlocaUsuarioProjetoDAO aDAO = new AlocaUsuarioProjetoDAO(Conexao.conectar());
                    aDAO.deleteAlocaUsuarioProjeto(projeto, u);

                    dispose();
                    ListaExcluirUsuario le = new ListaExcluirUsuario(usuario, projeto);
                    le.iniciar();
                }
            });

            i += 90;
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuarios)
                .addGap(338, 338, 338)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdicionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuarios)
                    .addComponent(btnAdicionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
                                   

    private void btnAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        ListaAddUsuario la = new ListaAddUsuario(this.projeto, this.usuario);
        dispose();
        la.iniciar();
    }
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        ProjetoPrincipal pp = new ProjetoPrincipal(this.projeto, this.usuario);
        dispose();
        pp.iniciar();
    }
    
    

    /**
     * @param args the command line arguments
     */
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        this.setVisible(true);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdicionarUsuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUsuarios;
    // End of variables declaration                   
}
